// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBMgg4PcTQmIs1KzDhuce5RFG8F0flTQ',
    appId: '1:932074157907:web:e5a87dae557b503dee93a6',
    messagingSenderId: '932074157907',
    projectId: 'flutter-crud-288a6',
    authDomain: 'flutter-crud-288a6.firebaseapp.com',
    storageBucket: 'flutter-crud-288a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdJqxS8DncMiFBy6g6boZ_IFe--p0kEI',
    appId: '1:932074157907:android:e7e949877af68267ee93a6',
    messagingSenderId: '932074157907',
    projectId: 'flutter-crud-288a6',
    storageBucket: 'flutter-crud-288a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhIgtUr4Ax-_jPukt2buuWc9966rxrCaM',
    appId: '1:932074157907:ios:f2d6d1762739de82ee93a6',
    messagingSenderId: '932074157907',
    projectId: 'flutter-crud-288a6',
    storageBucket: 'flutter-crud-288a6.appspot.com',
    iosClientId: '932074157907-07momb8gg2rva83nj661jnau34t1hbd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhIgtUr4Ax-_jPukt2buuWc9966rxrCaM',
    appId: '1:932074157907:ios:f2d6d1762739de82ee93a6',
    messagingSenderId: '932074157907',
    projectId: 'flutter-crud-288a6',
    storageBucket: 'flutter-crud-288a6.appspot.com',
    iosClientId: '932074157907-07momb8gg2rva83nj661jnau34t1hbd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev1',
  );
}
